id: P009654
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN4970
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྩ་བ།
  author: ''
  volumes:
    3a976359dadd4cccb2f10a88406d8ee9:
      image_group_id: I3CN4972
      title: ''
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
