id: I0FD89FA7
legacy_id: P009654
ocr_import_info:
  bdrc_scan_id: W3CN4970
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:26:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:53:01.329050+00:00'
last_modified: 2022-08-27 19:53:12.700496
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4970
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4970
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྩ་བ།
  author: རྨ་ལོ་ཙཱ་བ་དགེ་བའི་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.9694472837527219
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN4972:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4972
      total_pages: 188
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4972.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9694472837527219
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
