id: I0FD89FA7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:27:47+00:00'
last_modified: '2022-06-08T12:35:55.592167+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4970
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྩ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6218':
      image_group_id: I3CN4972
      title: ''
      total_pages: 188
      order: 1
      base_file: 6218.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
